# =========================================================
# MATCH TERMINALE -> FILO
# =========================================================
# Finestra di ricerca principale, coerente con il lato del terminale.
TERMINAL_SEARCH_OUTWARD = 16
TERMINAL_SEARCH_INWARD = 4
TERMINAL_DIRECTIONAL_HALFSPAN = 5

# Fallback semplice: se la finestra direzionale non trova nulla,
# cerchiamo in un piccolo quadrato attorno al terminale.
TERMINAL_SQUARE_FALLBACK_RADIUS = 12
LATERAL_TERMINAL_REMAP_MIN_GAP = 10
LATERAL_TERMINAL_REMAP_MAX_GAP = 80
LATERAL_TERMINAL_REMAP_Y_TOL = 14

# Se il pixel etichettato trovato è troppo lontano dal terminale,
# lo marchiamo come sospetto nel debug.
MAX_REASONABLE_SNAP_DISTANCE = 24.0
ANALOG_METER_FALLBACK_RADIUS = 140
ANALOG_METER_MAX_SNAP_DISTANCE = 160.0
NON_SHORTING_MULTI_TERMINAL_CLASSES = {
    "connector",
    "integrated_circuit",
    "mosfet",
    "npn_transistor",
    "operational_amplifier",
    "pnp_transistor",
    "transformer",
}

# =========================================================
# HEURISTICHE SPECIALI
# =========================================================
BJT_BASE_ALIGN_Y_TOL = 10
BJT_BASE_MAX_DX = 180
BJT_BASE_LABEL_MAX_GAP = 180

MOSFET_GATE_ALIGN_Y_TOL = 10
MOSFET_GATE_MAX_DX = 260
MOSFET_GATE_LABEL_MAX_GAP = 120
MOSFET_GATE_SUPPLY_ALIGN_Y_TOL = 85

OPAMP_AUX_EXTERNAL_MAX_DX = 12
OPAMP_AUX_EXTERNAL_MAX_DY = 180
OPAMP_AUX_LABEL_REMAP_X_TOL = 12
OPAMP_AUX_LABEL_REMAP_MIN_GAP = 6
OPAMP_AUX_LABEL_REMAP_MAX_GAP = 180
OUTWARD_STUB_REMAP_SOURCE_CLASSES = {
    "antenna",
}
OUTWARD_STUB_REMAP_SOURCE_SIDES = {
    "top",
    "bottom",
}
OUTWARD_STUB_REMAP_X_TOL = 12
OUTWARD_STUB_REMAP_MIN_GAP = 10
OUTWARD_STUB_REMAP_MAX_GAP = 140
OUTWARD_STUB_REMAP_MAX_LABEL_WIDTH = 26
HORIZONTAL_STUB_LABEL_MAX_GAP = 70
HORIZONTAL_STUB_LABEL_Y_TOL = 24
HORIZONTAL_STUB_SOURCE_CLASSES = {
    "diode",
    "led",
}
VERTICAL_STUB_NETWORK_MERGE_ENABLE = True
VERTICAL_STUB_SOURCE_MAX_TERMINALS = 2
VERTICAL_STUB_SOURCE_MAX_WIDTH = 12
VERTICAL_STUB_SOURCE_MIN_HEIGHT = 80
VERTICAL_STUB_TARGET_MIN_TERMINALS = 2
VERTICAL_STUB_TARGET_MIN_WIDTH = 24
VERTICAL_STUB_NETWORK_MAX_GAP = 28
VERTICAL_STUB_NETWORK_MIN_Y_OVERLAP = 36
VERTICAL_STUB_NETWORK_AMBIGUITY_MARGIN = 6
OBLIQUE_BRANCH_RECOVERY_ENABLE = True
OBLIQUE_BRANCH_SOURCE_CLASSES = {
    "diode",
    "led",
}
OBLIQUE_BRANCH_SOURCE_SIDES = {
    "left",
    "right",
}
OBLIQUE_BRANCH_SEARCH_HALF_WIDTH = 24
OBLIQUE_BRANCH_SEARCH_HALF_HEIGHT = 64
OBLIQUE_BRANCH_MAX_ABS_DX = 18
OBLIQUE_BRANCH_MIN_ABS_DY = 12
OBLIQUE_BRANCH_MAX_ABS_DY = 56
OBLIQUE_BRANCH_MIN_DISTANCE = 16.0
OBLIQUE_BRANCH_MAX_DISTANCE = 40.0
OBLIQUE_BRANCH_MIN_SUPPORT_PIXELS = 12
OBLIQUE_BRANCH_MIN_SUPPORT_RATIO = 0.48
COMPONENT_BODY_ERASE_PADDING = 3
COMPONENT_BODY_ERASE_EXCLUDED_CLASSES = {
    "terminal",
    "gnd",
    "ground",
}

PLAIN_CROSSING_SELF_SHORT_EXCLUDED_CLASSES = COMPONENT_BODY_ERASE_EXCLUDED_CLASSES | {
    "integrated_circuit",
}

BRIDGE_MIN_RUN = 25
BRIDGE_MIN_PIXELS_PER_DIRECTION = 6
BRIDGE_HUMP_Y_MIN = 1
BRIDGE_HUMP_Y_MAX = 8
BRIDGE_HUMP_X_MIN = 3
BRIDGE_HUMP_X_MAX = 14
BRIDGE_HUMP_COLLAPSE_RADIUS = 10
BRIDGE_CUT_HALF_WIDTH = 6
BRIDGE_CUT_HALF_HEIGHT = 8
BRIDGE_PROBE_DISTANCE = 18
BRIDGE_FILLED_NODE_RADIUS = 8
BRIDGE_FILLED_NODE_AREA_MIN = 135
BRIDGE_FILLED_NODE_STRONG_AREA_MIN = 135
BRIDGE_FILLED_NODE_CENTER_RADIUS = 3
BRIDGE_FILLED_NODE_CENTER_AREA_MIN = 35
BRIDGE_THICK_HUMP_ENABLE = True
BRIDGE_THICK_HUMP_Y_MAX = 18
BRIDGE_THICK_HUMP_FOOT_Y_MAX = 6
BRIDGE_THICK_HUMP_X_MAX = 22
BRIDGE_THICK_HUMP_MIN_FOOT_PIXELS = 2
BRIDGE_THICK_HUMP_MIN_SIDE_PIXELS = 4
BRIDGE_THICK_HUMP_MIN_SKELETON_Y_SPAN = 4
BRIDGE_THICK_HUMP_RELAXED_MIN_SKELETON_Y_SPAN = 1
BRIDGE_THICK_HUMP_STRONG_SCORE_MIN = 40.0
BRIDGE_THICK_HUMP_STRONG_MIN_FOOT_PIXELS = 4
BRIDGE_THICK_HUMP_STRONG_MIN_VERTICAL_PIXELS = 10
BRIDGE_THICK_HUMP_VERTICAL_SEARCH_RADIUS = 8
BRIDGE_THICK_HUMP_MIN_VERTICAL_PIXELS = 6
# Un candidato con arco quasi privo di sviluppo verticale e supporto
# perfettamente simmetrico sui due lati e' tipicamente il bordo di una
# giunzione a T/croce, non un vero ponticello. La soglia viene applicata solo
# dopo il collapse dei candidati, cosi' il falso arco puo' comunque assorbire
# i micro-gap prodotti dalla stessa giunzione.
BRIDGE_THICK_HUMP_LOW_SPAN_SYMMETRY_REJECT_MIN = 0.85
# Un arco ampio puo' avere uno skeleton locale quasi orizzontale nel punto
# candidato, ma resta sostenuto da una colonna verticale lunga. Questa evidenza
# distingue un vero ponticello dai due bordi corti di una giunzione spessa.
BRIDGE_THICK_HUMP_LOW_SPAN_VERTICAL_SUPPORT_KEEP_MIN = 40
BRIDGE_HUMP_MIN_ANCHOR_QUALITY = 3
BRIDGE_SINGLETON_MIN_HUMP_DISTANCE = 8.0
BRIDGE_BLUE_STYLE_THICK_HUMP_ONLY = True
BRIDGE_BLUE_STYLE_MIN_PIXEL_FRACTION = 0.15
BRIDGE_BLUE_STYLE_MIN_MEDIAN_BGR_DELTA = 10.0
BRIDGE_BLUE_STYLE_MIN_SATURATION = 20
BRIDGE_BLUE_STYLE_MIN_BLUE_DELTA = 20
MICRO_BRIDGE_MAX_SIDE_GAP = 5
MICRO_BRIDGE_MIN_SIDE_GAP = 1
MICRO_BRIDGE_MIN_HORIZONTAL_RUN = 6
MICRO_BRIDGE_VERTICAL_BAND_RADIUS = 4
MICRO_BRIDGE_VERTICAL_BAND_DEPTH = 24
MICRO_BRIDGE_MIN_VERTICAL_PIXELS = 3
MICRO_BRIDGE_TERMINAL_HORIZONTAL_BAND = 60.0
MICRO_BRIDGE_COLUMN_X_TOL = 8
MICRO_BRIDGE_COLUMN_MIN_Y_SPAN = 60
OFFSET_BRIDGE_ROW_Y_TOL = 6
OFFSET_BRIDGE_ROW_MAX_X_GAP = 8
OFFSET_BRIDGE_ROW_MIN_POINTS = 3
OFFSET_BRIDGE_ROW_MIN_X_SPAN = 6

PLAIN_CROSSING_SPLIT_ENABLE = True
PLAIN_CROSSING_MIN_RUN = 25
PLAIN_CROSSING_MIN_PIXELS_PER_DIRECTION = 6
PLAIN_CROSSING_DOT_RADIUS = 8
PLAIN_CROSSING_DOT_AREA_MIN = 210
PLAIN_CROSSING_CUT_HALF_WIDTH = 4
PLAIN_CROSSING_CUT_HALF_HEIGHT = 4
PLAIN_CROSSING_PROBE_DISTANCE = 18

# Gli incroci obliqui non attraversano necessariamente i quattro punti
# cardinali usati dall'euristica storica. Li rileviamo tramite quattro rami
# radiali, richiedendo due coppie quasi rettilinee e almeno quattro terminali
# sulla label da dividere.
RADIAL_CROSSING_CLUSTER_RADIUS = 6
RADIAL_CROSSING_CUT_HALF_SIZE = 6
RADIAL_CROSSING_MIN_BRANCH_PIXELS = 8
RADIAL_CROSSING_MIN_TERMINALS = 4
RADIAL_CROSSING_OPPOSITE_DOT_MAX = -0.72
RADIAL_CROSSING_AXIS_DOT_MAX = 0.92

# =========================================================
# DEBUG VISIVO
# =========================================================
SAVE_DEBUG_IMAGES = True
TEXT_FONT_SCALE = 0.42
TEXT_THICKNESS = 1
TEXT_OUTLINE_THICKNESS = 3
TERMINAL_RADIUS = 4
SNAP_RADIUS = 3

MATCHED_TERMINAL_COLOR = (0, 180, 0)      # verde
UNMATCHED_TERMINAL_COLOR = (0, 0, 255)    # rosso
SUSPICIOUS_TERMINAL_COLOR = (0, 165, 255) # arancione
PROBLEM_TERMINAL_COLOR = (0, 220, 255)    # giallo-arancio acceso
SNAP_POINT_COLOR = (255, 0, 0)            # blu
LINK_COLOR = (255, 0, 255)                # magenta
TEXT_COLOR = (255, 255, 0)                # giallo
TEXT_OUTLINE_COLOR = (0, 0, 0)            # nero
