circuit_id: a02

components:
  battery2.1:
    type: dc
    value: 5
    unit: V
    source: manual_from_vcc_label
    label_text: "VCC +5 V DC"

  resistor22.1:
    value: 10000
    unit: ohm
    source: manual_from_image_label
    label_text: "10k"

  capacitor4.1:
    value: 100
    unit: nF
    source: manual_from_image_label
    label_text: "100nF"

  switch25.1:
    state: open
    source: graph_json_state
    label_text: "SENSE"

nodes:
  connector5.1_pin1:
    label: VCC
    source: manual_from_image_label
    label_text: "VCC +5 V DC"

  connector5.1_pin4:
    label: GND
    spice_node: 0
    source: graph_json_gnd
