"""
Regole di prompt dedicate agli scenari diagnostici.

Questo modulo tiene separata la parte piu delicata dell'agente: come proporre
scenari futuri senza modificarli subito, senza sovrascrivere gli output base e
senza confondere l'utente con primitive troppo tecniche.

Lo step 11 resta read-only: queste funzioni generano solo testo per il prompt.
"""

from __future__ import annotations


def build_scenario_answer_format() -> list[str]:
    """Definisce come gli scenari devono apparire nella risposta dell'agente."""
    return [
        "   Per ogni scenario usa una forma a due livelli: prima una spiegazione user-friendly, poi un blocco tecnico breve.",
        "",
        "   Livello user-friendly:",
        "   - Titolo naturale: descrivi cosa si vuole provare, non solo la primitiva tecnica.",
        "   - Perche lo propongo: collega lo scenario alle evidenze SPICE e al problema utente.",
        "   - Cosa proverei: spiega in parole semplici la modifica simulativa.",
        "   - Cosa mi aspetto: indica cosa dovrebbe cambiare se l'ipotesi e corretta.",
        "   - Come lo verifichiamo: indica quali tensioni, correnti, log o grafici confrontare.",
        "   - Prossimo passo: cosa provare se lo scenario non conferma l'ipotesi.",
        "",
        "   Blocco tecnico per pipeline:",
        "   Usa un blocco JSON breve e non inventare campi non deducibili dalle evidenze.",
        "   Il blocco deve aiutare una futura pipeline a trasformare lo scenario in una run separata.",
        "   Campi consigliati: `scenario_id`, `title`, `hypothesis`, `actions`, `rerun_from`, `analysis`, `compare`.",
        "   Se un campo non e deducibile, usa `unknown` oppure omettilo.",
        "",
        "   Quando possibile, esprimi la modifica controllata usando primitive generali come:",
        "   `close_switch`, `open_switch`, `drive_node_voltage`, `change_source_value`,",
        "   `connect_nodes`, `disconnect_terminal`, `move_terminal`, `replace_with_equivalent`,",
        "   `run_op`, `run_tran`.",
        "",
        "   Ricorda che nella versione read-only questi scenari NON sono eseguiti.",
        "   Sono solo proposte per una fase successiva della pipeline.",
    ]


def build_scenario_operating_rules() -> list[str]:
    """Restituisce regole sintetiche sugli scenari per la sezione operating rules."""
    return [
        "A diagnostic scenario is a controlled hypothesis that can be verified by generating a scenario-specific Pipeline 2.0 run and rerunning ngspice.",
        "A scenario must never overwrite the original Pipeline 2.0 outputs.",
        "A scenario must start from copied base artifacts, modify only the scenario copies, and save separate scenario artifacts for comparison.",
        "Scenario artifacts must be created only after the user explicitly chooses one proposed scenario to execute.",
        "Suggest at most 3 candidate scenarios, ordered from simplest to most informative.",
        "Each scenario must be readable by a non-SPICE user first, and machine-oriented only in a short technical block after the explanation.",
        "The user-facing scenario title should describe the diagnostic idea naturally, for example `Alimentare il ramo della lampada`, not only `drive_node_voltage`.",
        "The technical block should be concise and should not replace the human explanation.",
        "Prefer natural scenarios that directly test the user's symptom using existing nodes, states and values before proposing graph-correction scenarios.",
        "Prefer acting on existing external inputs, supply labels, connector pins and recognized component states before directly forcing internal load nodes.",
        "If an upstream input node feeds a load, drive the upstream input first; direct forcing of the load node is a later model-isolation test, not an early natural scenario.",
        "The top 3 scenarios should be independently executable: if a scenario needs another action first, include that action in the same scenario JSON or present it only as a later follow-up.",
        "Do not propose `run_tran` alone when the base operating point does not power the relevant branch; include the required drive/source/state actions in the same scenario.",
        "If ngspice succeeds and graph/node-map evidence is internally coherent, the first scenarios should be value, source, analysis or state tests, not topology rewrites.",
        "Avoid `connect_nodes`, `disconnect_terminal` and `move_terminal` in the top 3 scenarios unless structured evidence strongly suggests a graph/topology error.",
        "If topology repair is only a later possibility, mention it as a next step instead of making it one of the first 3 scenarios.",
        "Do not propose graph-correction scenarios in the top 3 unless there is strong structured evidence that the Graph JSON is wrong.",
        "Scenarios can be iterative: if one scenario does not explain the problem, propose the next one or a combination of previous validated assumptions.",
    ]


def build_scenario_guidance() -> list[str]:
    """Spiega al modello cosa intendiamo per scenari diagnostici."""
    return [
        "A diagnostic scenario is not generic advice.",
        "It is a future, controlled, SPICE-verifiable test used to check whether a suspected cause explains the user's problem.",
        "",
        "Conceptual flow:",
        "",
        "```text",
        "base Pipeline 2.0 outputs",
        "-> agent proposes a diagnostic scenario",
        "-> pipeline validates the scenario",
        "-> pipeline creates separate scenario artifacts",
        "-> ngspice runs on the scenario netlist",
        "-> base result and scenario result are compared",
        "-> the agent updates the diagnosis",
        "```",
        "",
        "The base circuit must remain unchanged.",
        "A scenario run must be saved separately from the base run.",
        "In the read-only agent step, scenarios are only proposed. No scenario folder, copied artifact or modified netlist should be created yet.",
        "Scenario artifacts should be created later only when the user selects a specific proposed scenario, for example scenario 1, 2 or 3.",
        "The scenario runner should copy the original artifacts into a scenario-specific folder, then apply controlled modifications only to those copies.",
        "Original files such as `01_graph.json`, `03_node_map.json`, `04_values_bound.json`, `07_netlist.cir` and `08_spice_run.json` must remain unchanged.",
        "",
        "Scenario priority:",
        "",
        "1. Prefer the least invasive scenario that directly tests the observed symptom.",
        "2. Prefer actions on existing connector pins, supply labels, source values and recognized switch states before forcing internal load nodes.",
        "3. Prefer value/source/analysis/state scenarios before topology repair when the graph is coherent.",
        "4. Test individual hypotheses before proposing combined scenarios.",
        "5. Use combined scenarios only after the individual assumptions are meaningful, and include every required action in the same JSON block.",
        "6. Use graph-correction or topology-rewrite scenarios only when graph or SPICE evidence strongly supports a recognition/topology error.",
        "",
        "Naturalness caution:",
        "",
        "- If a load is fed through an upstream resistor or connector node, prefer driving that upstream node before directly driving the load terminal.",
        "- Directly driving a load terminal is useful only as a later isolation test for the load model, not as one of the first natural scenarios when an upstream input exists.",
        "- If an existing switch is recognized, a scenario that opens/closes that switch is usually more natural than inventing a new internal drive point.",
        "- A scenario must be executable on its own. Avoid wording such as `after scenario 1, run .tran` unless the technical JSON also includes the actions from scenario 1.",
        "- If `.tran` is useful, make it part of a complete scenario, for example drive a node and run transient analysis in the same scenario.",
        "",
        "Topology caution:",
        "",
        "- `connect_nodes`, `disconnect_terminal` and `move_terminal` are topology-rewrite actions.",
        "- Do not put topology-rewrite actions in the first 3 scenarios when ngspice succeeds and the graph/node map are coherent.",
        "- In that case, propose electrical tests first, for example driving an input node, changing a source value, closing an existing switch or running another analysis.",
        "- If topology may still be relevant, mention it as a possible later step after simpler scenarios are tested.",
        "- If ngspice fails, nodes are floating/singleton, critical components are missing, or Graph JSON warnings indicate recognition problems, topology-rewrite scenarios can be proposed earlier.",
        "",
        "Scenario presentation format:",
        "",
        "- Start with a natural title that a user can understand.",
        "- Explain why the scenario is proposed using concrete evidence from the base run.",
        "- Explain what would be changed in simple words.",
        "- Explain what SPICE result would confirm or reject the hypothesis.",
        "- End the scenario with a short technical JSON block for the future pipeline.",
        "- Keep the technical block small: it is a controlled hint for automation, not the main answer.",
        "",
        "Example technical block shape:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_1\",",
        "  \"title\": \"Alimentare il ramo della lampada\",",
        "  \"hypothesis\": \"The lamp branch is inactive because its input node is not driven.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"drive_node_voltage\",",
        "      \"target\": \"N002\",",
        "      \"value\": \"5V\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"04\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N002)\", \"v(N004)\", \"i(Rlamp13_1)\"]",
        "}",
        "```",
        "",
        "When proposing a scenario, reason about which part of the pipeline would need to be rerun.",
        "",
        "Pipeline rerun guidance:",
        "",
        "- If the scenario only changes a value, source amplitude, model parameter or analysis command, it may reuse `01_graph.json`, `02_normalized_circuit.json` and `03_node_map.json`, then regenerate from `04_values.py`, `06_component_rules.py`, `07_spice_emit.py` and `08_spice_run.py` as needed.",
        "- If the scenario changes the state of an already recognized component, for example closing an existing switch, it should create a scenario layer and then rerun the first affected step through `08`.",
        "- If the scenario combines actions, for example driving an input node and closing a switch, list both actions in the same JSON block so the scenario is self-contained.",
        "- If the scenario adds `.tran`, include the required electrical setup actions in the same scenario when the base circuit does not already energize the branch of interest.",
        "- If the scenario changes electrical topology, for example connecting/disconnecting nodes, it should be treated as topology-rewrite and used only when justified by the evidence.",
        "- If the scenario requires correcting the recognized Graph JSON itself, it is not just a normal electrical scenario. It should be treated as a graph-correction scenario, saved as a copied/modified scenario graph, and may need to restart from `01_io.py` or an equivalent scenario-specific graph input.",
        "- If the evidence only suggests a possible Graph JSON error but does not prove it, request image access instead of silently changing the graph.",
        "",
        "Image request policy:",
        "",
        "- Request the image when ngspice fails because the generated circuit is not electrically meaningful, for example singular matrix, floating nodes or topology-related convergence failure.",
        "- Request the image when Graph JSON warnings or node-map evidence indicate likely recognition errors.",
        "- Do not request the image just because a circuit branch is inactive in a successful and coherent SPICE run.",
        "- If image inspection would merely be useful for human confirmation, say so in the limitations but keep `Richiede immagine: no`.",
        "",
        "Do not directly decide implementation details as facts. State them as expected future pipeline behavior.",
        "For every scenario, state what should be compared between the base run and scenario run, for example node voltage, branch current, SPICE convergence, emitted/skipped components, stdout/stderr changes, transient waveform or load current.",
    ]
