"""
Regole di prompt dedicate agli scenari diagnostici.

Questo modulo tiene separata la parte piu delicata dell'agente: come proporre
scenari futuri senza modificarli subito, senza sovrascrivere gli output base e
senza confondere l'utente con primitive troppo tecniche.

Lo step 11 resta read-only: queste funzioni generano solo testo per il prompt.
"""

from __future__ import annotations


def build_scenario_answer_format() -> list[str]:
    """Definisce come gli scenari devono apparire nella risposta dell'agente."""
    return [
        "   Quando proponi scenari usa sempre una grammatica visiva stabile.",
        "   Per ogni scenario usa una forma a due livelli: prima una spiegazione user-friendly, poi un blocco tecnico breve.",
        "   Ogni scenario deve iniziare con un titolo nel formato `**scenario_1 - Titolo naturale**`.",
        "",
        "   Livello user-friendly:",
        "   - `Ipotesi:` collega lo scenario alle evidenze SPICE e al problema utente.",
        "   - `Cosa cambia:` spiega in parole semplici la modifica simulativa.",
        "   - `Cosa verifichiamo:` indica cosa dovrebbe cambiare se l'ipotesi e corretta.",
        "   - `Come lo leggiamo:` indica quali tensioni, correnti, log o grafici confrontare.",
        "   - `Se non basta:` indica il prossimo passo solo in una frase breve.",
        "",
        "   Blocco tecnico per pipeline:",
        "   Usa un blocco JSON breve e non inventare campi non deducibili dalle evidenze.",
        "   Il blocco deve aiutare una futura pipeline a trasformare lo scenario in una run separata.",
        "   Campi consigliati: `scenario_id`, `title`, `hypothesis`, `actions`, `rerun_from`, `analysis`, `compare`.",
        "   Per scenari di correzione topologica non ancora eseguibili puoi aggiungere anche `execution_mode` e `required_evidence`.",
        "   Non usare `unknown` dentro `actions[].value`: uno scenario eseguibile deve avere valori concreti.",
        "   Se un valore concreto non e deducibile, ometti l'azione eseguibile e descrivi lo scenario solo come follow-up non ancora eseguibile.",
        "",
        "   Primitive scenario disponibili:",
        "   - Scenari elettrici / di pilotaggio: `drive_node_voltage`, `set_initial_node_voltage`, `add_voltage_source_between_nodes`, `change_source_value`, `change_component_value`, `close_switch`.",
        "   - Scenari topologici controllati: `connect_nodes`, `add_resistor_between_nodes`, `feed_nodes_from_source_node`.",
        "   Primitive future, da citare solo se ben giustificate e non ancora eseguibili:",
        "   `open_switch`, `disconnect_terminal`, `move_terminal`, `replace_with_equivalent`, `run_op`, `run_tran`.",
        "",
        "   Dopo l'ultimo scenario aggiungi sempre una chiusura operativa breve, per esempio:",
        "   `Puoi scrivere: esegui scenario 1` oppure `esegui l'ultimo`.",
        "",
        "   Ricorda che nella versione read-only questi scenari NON sono eseguiti.",
        "   Sono solo proposte per una fase successiva della pipeline.",
    ]


def build_scenario_operating_rules() -> list[str]:
    """Restituisce regole sintetiche sugli scenari per la sezione operating rules."""
    return [
        "A diagnostic scenario is a controlled hypothesis that can be verified by generating a scenario-specific Pipeline 2.0 run and rerunning ngspice.",
        "A scenario must never overwrite the original Pipeline 2.0 outputs.",
        "A scenario must start from copied base artifacts, modify only the scenario copies, and save separate scenario artifacts for comparison.",
        "Scenario artifacts must be created only after the user explicitly chooses one proposed scenario to execute.",
        "Suggest at most 3 candidate scenarios, ordered from simplest to most informative.",
        "The global budget is at most 5 executed scenarios per circuit.",
        "In the initial diagnostic answer, the first set of up to 3 scenarios must be simple first-pass candidates, not combined scenarios.",
        "Each scenario must be readable by a non-SPICE user first, and machine-oriented only in a short technical block after the explanation.",
        "The user-facing scenario title should describe the diagnostic idea naturally, for example `Alimentare il ramo della lampada`, not only `drive_node_voltage`.",
        "The technical block should be concise and should not replace the human explanation.",
        "For executable scenario JSON, use only action types currently supported by the scenario runner unless clearly marked as future/not executable.",
        "Current scenario families are electrical/drive scenarios (`drive_node_voltage`, `set_initial_node_voltage`, `add_voltage_source_between_nodes`, `change_source_value`, `change_component_value`, `close_switch`) and controlled topological scenarios (`connect_nodes`, `add_resistor_between_nodes`, `feed_nodes_from_source_node`).",
        "Never put `unknown` in `actions[].value`; use a concrete SPICE value such as `5V`, `10V`, `DC 3.3`, or `SIN(0 1 100)`.",
        "Prefer natural scenarios that directly test the user's symptom using existing nodes, states and values before proposing graph-correction scenarios.",
        "Prefer `change_component_value` when the hypothesis is about an already emitted resistor, capacitor, inductor, RC constant, bias network or equivalent simple load value.",
        "Use `change_source_value` only for real SPICE sources already present in the netlist.",
        "Use `add_voltage_source_between_nodes` when the base netlist lacks a realistic external excitation and the natural diagnostic move is to power the circuit from existing interface nodes such as connector pins, supply labels or input/return nodes.",
        "Prefer `add_voltage_source_between_nodes` over `drive_node_voltage` when the goal is to energize the whole circuit or a whole input path, not only to isolate a single internal branch node.",
        "Place `add_voltage_source_between_nodes` on existing external interface nodes whenever possible, not directly on internal load nodes, unless no more natural input nodes exist.",
        "Use `drive_node_voltage` mainly as an isolation action when a value/source/switch scenario would be less natural.",
        "Use `set_initial_node_voltage` only with `analysis: tran` when an otherwise valid symmetric circuit needs an initial imbalance; it writes `.ic`, adds no permanent source and is not a power-supply action.",
        "Use `connect_nodes` when the hypothesis is a missing continuity, jumper, bridge, wire, connector-to-branch link or controlled path between two nodes that already exist in the node map.",
        "Use `add_resistor_between_nodes` when the hypothesis requires a new resistive branch between two existing nodes, for example an added bias path, pull-up, pull-down, shunt or weak coupling branch that is not already present in the netlist.",
        "For `add_resistor_between_nodes`, choose a concrete resistor value and prefer simple circuit-scale values that are already plausible in the current schematic family.",
        "Prefer `connect_nodes` only when this is more natural than closing an existing switch or driving a real upstream input node.",
        "Do not use `add_resistor_between_nodes` when the only goal is changing the value of a resistor that already exists in the emitted netlist; use `change_component_value` for that case.",
        "Use `feed_nodes_from_source_node` when there is a source node that is already powered in the base run, or made powered by another action in the same self-contained scenario, and the hypothesis is that this supply should propagate to one or more target branch-input nodes.",
        "Prefer `feed_nodes_from_source_node` over multiple separate `connect_nodes` only when the diagnostic idea is explicitly supply propagation from one source node to one or more targets.",
        "Do not use `feed_nodes_from_source_node` when the base netlist has no active source node; in that case prefer `add_voltage_source_between_nodes` for realistic circuit excitation, or `drive_node_voltage` only for a later isolation test.",
        "If ngspice failed and the evidence shows strong topology problems, do not stay in simple electrical-test mode: switch to image-guided topology-correction reasoning.",
        "Prefer acting on existing external inputs, supply labels, connector pins and recognized component states before directly forcing internal load nodes.",
        "If an upstream input node feeds a load, drive the upstream input first; direct forcing of the load node is a later model-isolation test, not an early natural scenario.",
        "The top 3 scenarios should be independently executable: if a scenario needs another action first, include that action in the same scenario JSON or present it only as a later follow-up.",
        "Do not propose combined scenarios in the initial top 3. Combined scenarios are allowed only after earlier scenarios have been executed and the user asks what to try next.",
        "Because every scenario run starts again from the base run, any next scenario proposed after executed evidence must be executable from the base run on its own.",
        "If a next scenario depends on an enabling condition demonstrated by an earlier scenario, include that enabling action again in the same `actions` array.",
        "Do not propose a follow-up scenario that relies on the user mentally carrying over actions from a previous scenario run.",
        "Do not propose `run_tran` alone when the base operating point does not power the relevant branch; include the required drive/source/state actions in the same scenario.",
        "If all initially proposed scenarios have been executed and none is a resolved candidate, propose the next most informative scenario instead of stopping.",
        "If only one executable scenario remains in the budget, propose only one final scenario and make it explicit that a final conclusion must follow after its execution.",
        "If no executable scenario remains in the budget, do not propose any new scenario: provide a final diagnostic conclusion from the accumulated evidence.",
        "If the user explicitly asks for a final conclusion, a final diagnosis, a summary of executed scenarios, or whether it makes sense to stop, switch from next-scenario reasoning to final-conclusion reasoning.",
        "In final-conclusion reasoning, use the executed scenario evidence as the primary basis and do not automatically force a new scenario just because budget still exists.",
        "In final-conclusion reasoning, propose one more scenario only when it is clearly the single remaining decisive test.",
        "The next scenario may combine actions, but only combine assumptions that were supported by previous scenario evidence; do not combine all scenarios blindly.",
        "`not_resolved` means that a scenario was not sufficient by itself; it does not automatically mean the action is useless.",
        "A `not_resolved` scenario can still be an enabling action in a combined scenario if it closes a switch, creates a reference path, completes a current path, or supplies a missing precondition for another useful action.",
        "When a `not_resolved` scenario is enabling for the next hypothesis, the next hypothesis must be proposed as a new self-contained scenario that includes both the enabling action and the new action.",
        "When one executed scenario has already changed the symptom-linked nodes or branches, prefer extending that proven direction before proposing a weaker exploratory source-change scenario.",
        "Prefer combining the strongest symptom-linked scenario with an enabling action before proposing a generic source-value variation, unless the source itself is the strongest evidence-backed hypothesis.",
        "When proposing a combined scenario, explain why each included action is justified and why excluded actions are not included yet.",
        "If ngspice succeeds and graph/node-map evidence is internally coherent, the first scenarios should be value, source, analysis or state tests, not topology rewrites.",
        "If ngspice failed and the evidence shows no ground/reference, critical singleton nodes, skipped critical components, or isolated branches, prefer topology-correction scenarios over simple drive/source scenarios.",
        "In topology-correction mode, the first 3 scenarios may include future graph-correction or image-guided reconstruction scenarios even if the current runner cannot execute them yet.",
        "When a topology-correction scenario is not executable yet, clearly mark it as future/not executable instead of pretending it can already be run by the current pipeline.",
        "Avoid `disconnect_terminal` and `move_terminal` in the top 3 scenarios unless structured evidence strongly suggests a graph/topology error.",
        "Use `connect_nodes` in the top 3 only when the main hypothesis is a missing continuity between already recognized nodes, not as a generic shortcut for powering a branch.",
        "Use `feed_nodes_from_source_node` in the top 3 only when the base evidence clearly identifies one powered source node and one or more unpowered branch-input target nodes.",
        "If topology repair is only a later possibility, mention it as a next step instead of making it one of the first 3 scenarios.",
        "Do not propose graph-correction scenarios in the top 3 unless there is strong structured evidence that the Graph JSON is wrong.",
        "Scenarios can be iterative: if one scenario does not explain the problem, propose the next one or a combination of previous validated assumptions.",
    ]


def build_scenario_guidance() -> list[str]:
    """Spiega al modello cosa intendiamo per scenari diagnostici."""
    return [
        "A diagnostic scenario is not generic advice.",
        "It is a future, controlled, SPICE-verifiable test used to check whether a suspected cause explains the user's problem.",
        "",
        "Conceptual flow:",
        "",
        "```text",
        "base Pipeline 2.0 outputs",
        "-> agent proposes a diagnostic scenario",
        "-> pipeline validates the scenario",
        "-> pipeline creates separate scenario artifacts",
        "-> ngspice runs on the scenario netlist",
        "-> base result and scenario result are compared",
        "-> the agent updates the diagnosis",
        "```",
        "",
        "The base circuit must remain unchanged.",
        "A scenario run must be saved separately from the base run.",
        "In the read-only agent step, scenarios are only proposed. No scenario folder, copied artifact or modified netlist should be created yet.",
        "Scenario artifacts should be created later only when the user selects a specific proposed scenario, for example scenario 1, 2 or 3.",
        "The scenario runner should copy the original artifacts into a scenario-specific folder, then apply controlled modifications only to those copies.",
        "Original files such as `01_graph.json`, `03_node_map.json`, `04_values_bound.json`, `07_netlist.cir` and `08_spice_run.json` must remain unchanged.",
        "A single circuit should not exceed 5 executed scenarios in total.",
        "",
        "Scenario priority:",
        "",
        "1. Prefer the least invasive scenario that directly tests the observed symptom.",
        "2. Prefer actions on existing connector pins, supply labels, source values and recognized switch states before forcing internal load nodes.",
        "2b. When the uncertainty is mainly about a resistor, capacitor, inductor or equivalent load value already present in netlist, prefer `change_component_value` before inventing a new internal drive.",
        "3. Prefer value/source/analysis/state scenarios before topology repair when the graph is coherent.",
        "3b. If ngspice failed with strong topology evidence, request the image and move early to topology-correction reasoning instead of staying in simple electrical-test mode.",
        "4. In the first response, propose only single-hypothesis scenarios, not combined scenarios.",
        "5. Test individual hypotheses before proposing combined scenarios.",
        "6. Use combined scenarios only after the individual assumptions are meaningful, and include every required action in the same JSON block.",
        "7. Use graph-correction or topology-rewrite scenarios only when graph or SPICE evidence strongly supports a recognition/topology error.",
        "8. After executed scenarios are available, use their outcomes to decide whether the next scenario should be single-action, combined, or a request for missing evidence.",
        "",
        "After executed scenarios:",
        "",
        "- If at least one scenario is `resolved_candidate` with `stop_automation=true`, do not propose a new scenario unless the user explicitly asks for further exploration.",
        "- If only one executable scenario remains, propose only one final scenario and state that the next answer after execution must be a final diagnostic conclusion.",
        "- If no executable scenario remains, stop proposing scenarios and provide a final diagnostic conclusion based on all executed evidence.",
        "- If the user asks for a final conclusion before the budget is exhausted, switch to final-conclusion reasoning: summarize the executed scenarios, strengthen or weaken the hypotheses, and avoid proposing a new scenario by default.",
        "- In that final-conclusion reasoning, suggest an additional scenario only if it is clearly the single remaining decisive test.",
        "- If no scenario is resolved and at least one scenario is `partially_resolved`, propose a next scenario that combines only the useful partial assumptions.",
        "- Do not exclude a scenario only because its outcome is `not_resolved`: first decide whether it is irrelevant, or whether it is an enabling condition that may become useful together with another action.",
        "- Treat `not_resolved` but enabling actions as candidates for combined scenarios when they close a switch, create a DC reference, complete a path, or provide a precondition that another scenario lacked.",
        "- If one scenario already changed the nodes or currents most closely tied to the user's symptom, treat that scenario as the main direction for the next step.",
        "- In that case, prefer adding only the minimum enabling action needed around that main direction before testing broader source-value variations.",
        "- If all scenarios are `not_resolved`, explain that the current hypotheses did not work and propose a different minimal hypothesis, or request missing evidence if needed.",
        "- Do not combine all previously proposed scenarios automatically. Combining actions is useful only when the previous results show complementary evidence.",
        "- A combined scenario must be self-contained: include every required action in the same `actions` array.",
        "- Because each scenario run restarts from the base run, a next scenario must not depend on actions applied only in a previous scenario folder.",
        "- If the next hypothesis needs an enabling action already tested earlier, repeat that action inside the new scenario JSON together with the new action.",
        "",
        "Naturalness caution:",
        "",
        "- If the base run has no realistic external excitation, first consider `add_voltage_source_between_nodes` on the natural circuit interface before directly forcing an internal node.",
        "- If a load is fed through an upstream resistor or connector node, prefer driving that upstream node before directly driving the load terminal.",
        "- Directly driving a load terminal is useful only as a later isolation test for the load model, not as one of the first natural scenarios when an upstream input exists.",
        "- If an existing switch is recognized, a scenario that opens/closes that switch is usually more natural than inventing a new internal drive point.",
        "- A scenario must be executable on its own. Avoid wording such as `after scenario 1, run .tran` unless the technical JSON also includes the actions from scenario 1.",
        "- If `.tran` is useful, make it part of a complete scenario, for example drive a node and run transient analysis in the same scenario.",
        "",
        "Topology caution:",
        "",
        "- `connect_nodes`, `add_resistor_between_nodes`, `feed_nodes_from_source_node`, `disconnect_terminal` and `move_terminal` belong to controlled topological scenarios.",
        "- `connect_nodes` is the minimal topological scenario: use it for controlled continuity hypotheses between nodes already recognized by the pipeline.",
        "- `add_resistor_between_nodes` is the controlled resistive-branch scenario: use it when the diagnosis calls for adding a new resistor between two existing nodes instead of changing an already emitted resistor value.",
        "- `feed_nodes_from_source_node` is the supply-propagation scenario: use it when a known powered node should feed one or more target branch-input nodes.",
        "- Do not put heavy topology-rewrite actions in the first 3 scenarios when ngspice succeeds and the graph/node map are coherent.",
        "- In coherent runs, `connect_nodes` can still appear among the first 3 scenarios when the evidence specifically suggests a missing bridge or continuity path between existing nodes.",
        "- In that case, propose electrical tests first, for example driving an input node, changing a source value, closing an existing switch or running another analysis.",
        "- If topology may still be relevant, mention it as a possible later step after simpler scenarios are tested.",
        "- If ngspice fails, nodes are floating/singleton, critical components are missing, or Graph JSON warnings indicate recognition problems, topology-rewrite scenarios can be proposed earlier.",
        "- If ngspice fails and there is strong structured evidence of topology error, do not keep proposing only `drive_node_voltage` or `change_source_value` as if the extracted graph were already trustworthy.",
        "- In that case, the agent should switch to topology-correction mode: explain the failure, request the real image, and propose correction scenarios for graph structure or missing interpreted components.",
        "- In topology-correction mode, it is acceptable that a proposed scenario is not immediately executable by the current scenario runner, as long as this is stated clearly.",
        "- In topology-correction mode, prefer scenarios such as reconstructing a split source, restoring a missing reference, reconnecting singleton terminals, or reinterpreting a relay/transformer/contact structure from the image.",
        "",
        "Scenario presentation format:",
        "",
        "- Start with a natural title that a user can understand.",
        "- Explain why the scenario is proposed using concrete evidence from the base run.",
        "- Explain what would be changed in simple words.",
        "- Explain what SPICE result would confirm or reject the hypothesis.",
        "- End the scenario with a short technical JSON block for the future pipeline.",
        "- Keep the technical block small: it is a controlled hint for automation, not the main answer.",
        "- The executable technical JSON should use only the currently available scenario primitives: `drive_node_voltage`, `set_initial_node_voltage`, `add_voltage_source_between_nodes`, `change_source_value`, `change_component_value`, `close_switch`, `connect_nodes`, `add_resistor_between_nodes`, `feed_nodes_from_source_node`.",
        "- If the scenario is not executable yet, say so explicitly and use future-oriented actions only as a structured proposal.",
        "- For `change_source_value`, choose a concrete value that makes the diagnostic comparison meaningful; do not write `unknown`.",
        "- Use `change_source_value` as the next scenario only when varying the existing source is more evidence-backed than extending an already successful symptom-linked node or state test.",
        "- For `change_component_value`, target a component name already visible in the emitted netlist, for example `Rresistor22_4`, or a component id that clearly resolves to it, for example `resistor22.4`.",
        "- Use `change_component_value` for bias resistors, RC timing parts, simple loads or equivalent components, not for sources or transistor/diode models.",
        "- For `change_source_value`, prefer the SPICE source name visible in the netlist, for example `Vbattery2_1`; component ids such as `battery2.1` are accepted only if the runner can resolve them.",
        "- For `close_switch`, target an existing recognized switch component such as `switch25.1`; do not invent a switch.",
        "- If no concrete source value is justified, describe the idea in the prose and do not include it as an executable JSON action.",
        "- In `compare`, use SPICE quantities such as `v(N001)` or `i(vbattery2_1#branch)` that are directly tied to the user symptom.",
        "- Every executable scenario must include a non-empty `expect` object. Its keys must also appear in `compare` and its values must be one of: `activated`, `deactivated`, `changed`, `unchanged`, `increased`, `decreased`, `magnitude_increased`, `magnitude_decreased`, `nonzero`.",
        "- Put in `expect` only the minimal observable result that would confirm or reject the hypothesis; a scenario without it cannot be registered for execution.",
        "- Every branch, load, output, or component that the scenario claims to activate, preserve, or modify must have at least one directly related observable in `compare`.",
        "- For a compound scenario involving multiple branches or outputs, include one observable for each of them; prefer branch current when available, otherwise use the relevant output or node voltage.",
        "- Do not claim that a branch remains active or changes successfully unless the proposed `compare` quantities can verify that claim.",
        "- Use `stderr` in `compare` only when the scenario is explicitly testing convergence, warning reduction, missing reference conditions, or another numerical/topological issue.",
        "- Do not add `stderr` as a default extra comparison when node voltages or branch currents already test the hypothesis directly.",
        "",
        "Example technical block shape:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_1\",",
        "  \"title\": \"Alimentare il ramo della lampada\",",
        "  \"hypothesis\": \"The lamp branch is inactive because its input node is not driven.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"drive_node_voltage\",",
        "      \"target\": \"N002\",",
        "      \"value\": \"5V\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"04\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N002)\", \"v(N004)\", \"i(Rlamp13_1)\"],",
        "  \"expect\": {\"v(N002)\": \"increased\"}",
        "}",
        "```",
        "",
        "Example external-supply scenario action:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_2\",",
        "  \"title\": \"Alimentare il circuito dal connettore di ingresso\",",
        "  \"hypothesis\": \"The extracted netlist stays inactive because the circuit is not receiving a realistic external excitation on its natural interface nodes.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"add_voltage_source_between_nodes\",",
        "      \"positive\": \"N003\",",
        "      \"negative\": \"0\",",
        "      \"value\": \"5V\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"07\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N003)\", \"v(N001)\"]",
        "}",
        "```",
        "",
        "Example source-value scenario action:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_2\",",
        "  \"title\": \"Variare la sorgente principale\",",
        "  \"hypothesis\": \"Changing the existing supply should affect only the branches connected to that supply.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"change_source_value\",",
        "      \"target\": \"VVCC\",",
        "      \"value\": \"10V\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"07\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N001)\", \"i(vvcc#branch)\"]",
        "}",
        "```",
        "",
        "Example component-value scenario action:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_3\",",
        "  \"title\": \"Ridurre la resistenza di bias della base\",",
        "  \"hypothesis\": \"A lower bias resistance should increase the transistor drive if the current bias network is too weak.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"change_component_value\",",
        "      \"target\": \"Rresistor22_4\",",
        "      \"value\": \"33k\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"07\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N004)\", \"v(N005)\"]",
        "}",
        "```",
        "",
        "Example close-switch scenario action:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_1\",",
        "  \"title\": \"Chiudere lo switch riconosciuto\",",
        "  \"hypothesis\": \"The open switch may be preventing a useful reference or current path.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"close_switch\",",
        "      \"target\": \"switch25.1\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"06\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N001)\", \"i(vbattery2_1#branch)\"]",
        "}",
        "```",
        "",
        "Example connect-nodes scenario action:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_2\",",
        "  \"title\": \"Collegare il nodo alimentato al ramo LED\",",
        "  \"hypothesis\": \"The branch may stay inactive because the powered node is not electrically continuous with the branch input.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"connect_nodes\",",
        "      \"from\": \"N002\",",
        "      \"to\": \"N003\",",
        "      \"resistance\": \"1m\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"07\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N002)\", \"v(N003)\", \"i(Rresistor22_1)\"]",
        "}",
        "```",
        "",
        "Example add-resistor-between-nodes scenario action:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_3\",",
        "  \"title\": \"Aggiungere un ramo resistivo di bias verso la base\",",
        "  \"hypothesis\": \"The current branch may stay weak because the base or trigger path lacks a useful resistive coupling branch.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"add_resistor_between_nodes\",",
        "      \"from\": \"N001\",",
        "      \"to\": \"N004\",",
        "      \"value\": \"33k\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"07\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N001)\", \"v(N004)\", \"v(N003)\"]",
        "}",
        "```",
        "",
        "Example feed-nodes scenario action:",
        "",
        "```json",
        "{",
        "  \"scenario_id\": \"scenario_3\",",
        "  \"title\": \"Propagare il nodo alimentato verso il ramo lampada\",",
        "  \"hypothesis\": \"The lamp branch is inactive because the powered source node does not reach the branch input.\",",
        "  \"actions\": [",
        "    {",
        "      \"type\": \"feed_nodes_from_source_node\",",
        "      \"source_node\": \"N001\",",
        "      \"target_nodes\": [\"N002\"],",
        "      \"resistance\": \"1m\"",
        "    }",
        "  ],",
        "  \"rerun_from\": \"07\",",
        "  \"analysis\": \"op\",",
        "  \"compare\": [\"v(N001)\", \"v(N002)\", \"v(N004)\", \"i(Rlamp13_1)\"]",
        "}",
        "```",
        "",
        "When proposing a scenario, reason about which part of the pipeline would need to be rerun.",
        "",
        "Pipeline rerun guidance:",
        "",
        "- If the scenario only changes a value, source amplitude, model parameter or analysis command, it may reuse `01_graph.json`, `02_normalized_circuit.json` and `03_node_map.json`, then regenerate from `04_values.py`, `06_component_rules.py`, `07_spice_emit.py` and `08_spice_run.py` as needed.",
        "- If the scenario changes the state of an already recognized component, for example closing an existing switch, it should create a scenario layer and then rerun the first affected step through `08`.",
        "- If the scenario combines actions, for example driving an input node and closing a switch, list both actions in the same JSON block so the scenario is self-contained.",
        "- After scenarios have already been executed, do not write a next scenario as if previous scenario actions were still active; include the required prior action again in the new JSON block.",
        "- If the scenario adds `.tran`, include the required electrical setup actions in the same scenario when the base circuit does not already energize the branch of interest.",
        "- If the scenario changes electrical topology, for example connecting/disconnecting nodes, it should be treated as topology-rewrite and used only when justified by the evidence.",
        "- If the scenario requires correcting the recognized Graph JSON itself, it is not just a normal electrical scenario. It should be treated as a graph-correction scenario, saved as a copied/modified scenario graph, and may need to restart from `01_io.py` or an equivalent scenario-specific graph input.",
        "- If the scenario depends on image-guided graph correction, state that it is a future scenario run that would start from a copied graph artifact before regenerating the downstream steps.",
        "- If the evidence only suggests a possible Graph JSON error but does not prove it, request image access instead of silently changing the graph.",
        "",
        "Image request policy:",
        "",
        "- Request the image when ngspice fails because the generated circuit is not electrically meaningful, for example singular matrix, floating nodes or topology-related convergence failure.",
        "- When ngspice fails together with strong topology evidence such as `ground_groups_count = 0`, critical singleton nodes, skipped critical components, isolated branches or split power sources, image request should normally be `Richiede immagine: si`.",
        "- Request the image when Graph JSON warnings or node-map evidence indicate likely recognition errors.",
        "- Do not request the image just because a circuit branch is inactive in a successful and coherent SPICE run.",
        "- If image inspection would merely be useful for human confirmation, say so in the limitations but keep `Richiede immagine: no`.",
        "",
        "Do not directly decide implementation details as facts. State them as expected future pipeline behavior.",
        "For every scenario, state what should be compared between the base run and scenario run, for example node voltage, branch current, SPICE convergence, emitted/skipped components, stdout/stderr changes, transient waveform or load current.",
    ]
